# Generated by Django 4.0.4 on 2022-04-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='peinture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('peintre', models.CharField(max_length=100)),
                ('date_parution', models.DateField(blank=True, null=True)),
                ('mouvement_artistique', models.CharField(max_length=100)),
                ('idee', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
