# Generated by Django 4.0.4 on 2022-05-17 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('R209app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='peinture',
            new_name='tableaux',
        ),
    ]
